spring:
  application:
    name: query-dsl-2025-05-02

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.H2Dialect
      default_batch_fetch_size: 100
      format_sql: true
      highlight_sql: true
      use_sql_comments: true

  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.security: DEBUG
    org.example.querydsl20250502: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.batch: INFO